server:
  port: 8084

spring:
  application:
    name: Users
  datasource:
    url: jdbc:h2:tcp://localhost:9090/mem:wookie_books
    username: wookie
    password: wookie_books
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
